apiVersion: v1
kind: Pod
metadata:
  labels:
    app: qserv
  name: master
spec:
  containers:
  - command:
    - sh
    - /config-start/mariadb-start.sh
    image: qserv/mariadb_scisql:10.1.25
    imagePullPolicy: Always
    name: mariadb
    volumeMounts:
    - mountPath: /config-mariadb
      name: config-my-dot-cnf
    - mountPath: /config-start
      name: config-mariadb-start
    - mountPath: /qserv/run/var/log
      name: log-volume
    - mountPath: /qserv/run/tmp
      name: tmp-volume
    - mountPath: /qserv/data
      name: data-volume
  - command:
    - sh
    - /config-start/start.sh
    image: qserv/qserv:dev
    imagePullPolicy: Always
    name: master
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
    volumeMounts:
    - mountPath: /config-start
      name: config-master-start
    - mountPath: /qserv/run/var/log
      name: log-volume
    - mountPath: /qserv/run/tmp
      name: tmp-volume
    - mountPath: /qserv/data
      name: data-volume
    - mountPath: /qserv/run
      name: run-volume
  hostNetwork: true
  hostname: master
  initContainers:
  - command:
    - bash
    - /config/qserv-configure.sh
    env:
    - name: NODE_TYPE
      value: master
    - name: QSERV_MASTER
      value: kube-node-1
    image: qserv/qserv:dev
    imagePullPolicy: Always
    name: init-run-dir
    volumeMounts:
    - mountPath: /qserv/run
      name: run-volume
    - mountPath: /config/
      name: config-qserv-configure
  - command:
    - sh
    - /config-mariadb/mariadb-configure.sh
    image: qserv/mariadb_scisql:10.1.25
    imagePullPolicy: Always
    name: init-data-dir
    volumeMounts:
    - mountPath: /qserv/data
      name: data-volume
    - mountPath: /config-mariadb/
      name: config-mariadb-configure
    - mountPath: /config-sql
      name: config-master-sql
  nodeSelector:
    kubernetes.io/hostname: kube-node-1
  restartPolicy: Never
  subdomain: qserv
  volumes:
  - configMap:
      name: config-mariadb-configure
    name: config-mariadb-configure
  - configMap:
      name: config-mariadb-start
    name: config-mariadb-start
  - configMap:
      name: config-master-sql
    name: config-master-sql
  - configMap:
      name: config-master-start
    name: config-master-start
  - configMap:
      name: config-my-dot-cnf
    name: config-my-dot-cnf
  - configMap:
      name: config-qserv-configure
    name: config-qserv-configure
  - hostPath:
      path: /qserv/log
    name: log-volume
  - hostPath:
      path: /qserv/tmp
    name: tmp-volume
  - emptyDir: {}
    name: data-volume
  - emptyDir: {}
    name: run-volume
