sudo: required
services: docker
language: minimal

env:

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblz4-tool
  - ./install-dind.sh

script:
  # building k8s may cause Travis to time out w/o output
  - if [ -n "${TWAIT}" ]; then travis_wait 35 ./test.sh; else ./test.sh; fi
