apiVersion: v1
kind: PersistentVolume
metadata:
    name: qserv-1
    labels:
        dataid: "1"
spec:
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: qserv-local-storage
    local:
        path: /qserv/data
    nodeAffinity:
        required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - benjamin-worker-1
