apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: qserv-pvc-1
spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 10Gi
    storageClassName: qserv-local-storage
    selector:
        matchLabels:
            dataid: "1"
